name: "Docker"

on:
    push: null
    workflow_dispatch: null

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    build:
        name: "Build"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 10
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Build images"
            run: |
                docker --version
                export DOCKER_BUILDKIT="1"
                docker build .
